"""initial

Revision ID: 2634a08aa452
Revises: 
Create Date: 2022-09-01 15:46:34.993789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2634a08aa452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queries',
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.String(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=True),
    sa.Column('cluster', sa.String(), nullable=True),
    sa.Column('pub_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('query_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queries')
    # ### end Alembic commands ###
